sonar.projectKey=FordFly_Cypress-Cucumber-BDD
sonar.organization=fordfly
sonar.sources=cypress
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=cypress/reports/lcov.info
sonar.sourceEncoding=UTF-8
